// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todus.proto

#include "todus_windows.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace toDusPB {
constexpr SolicitudSMS::SolicitudSMS(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : telefono_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , id_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct SolicitudSMSDefaultTypeInternal {
  constexpr SolicitudSMSDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SolicitudSMSDefaultTypeInternal() {}
  union {
    SolicitudSMS _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SolicitudSMSDefaultTypeInternal _SolicitudSMS_default_instance_;
constexpr SolicitudFichaSolicitud::SolicitudFichaSolicitud(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : telefono_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , id_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , codigo_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct SolicitudFichaSolicitudDefaultTypeInternal {
  constexpr SolicitudFichaSolicitudDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SolicitudFichaSolicitudDefaultTypeInternal() {}
  union {
    SolicitudFichaSolicitud _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SolicitudFichaSolicitudDefaultTypeInternal _SolicitudFichaSolicitud_default_instance_;
constexpr RecepcionFichaSolicitud_DatosUsuario::RecepcionFichaSolicitud_DatosUsuario(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : telefono_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , nombre_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , enlacefoto_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , reservado1_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , reservado2_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct RecepcionFichaSolicitud_DatosUsuarioDefaultTypeInternal {
  constexpr RecepcionFichaSolicitud_DatosUsuarioDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~RecepcionFichaSolicitud_DatosUsuarioDefaultTypeInternal() {}
  union {
    RecepcionFichaSolicitud_DatosUsuario _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT RecepcionFichaSolicitud_DatosUsuarioDefaultTypeInternal _RecepcionFichaSolicitud_DatosUsuario_default_instance_;
constexpr RecepcionFichaSolicitud::RecepcionFichaSolicitud(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : fichasolicitud_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , usuario_(nullptr){}
struct RecepcionFichaSolicitudDefaultTypeInternal {
  constexpr RecepcionFichaSolicitudDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~RecepcionFichaSolicitudDefaultTypeInternal() {}
  union {
    RecepcionFichaSolicitud _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT RecepcionFichaSolicitudDefaultTypeInternal _RecepcionFichaSolicitud_default_instance_;
constexpr SolicitudFichaAcceso::SolicitudFichaAcceso(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : telefono_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , fichasolicitud_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , numeroversion_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct SolicitudFichaAccesoDefaultTypeInternal {
  constexpr SolicitudFichaAccesoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SolicitudFichaAccesoDefaultTypeInternal() {}
  union {
    SolicitudFichaAcceso _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SolicitudFichaAccesoDefaultTypeInternal _SolicitudFichaAcceso_default_instance_;
constexpr RecepcionFichaAcceso::RecepcionFichaAcceso(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : fichaacceso_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , reservado1_(0)
  , tiempoexpiracion_(0){}
struct RecepcionFichaAccesoDefaultTypeInternal {
  constexpr RecepcionFichaAccesoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~RecepcionFichaAccesoDefaultTypeInternal() {}
  union {
    RecepcionFichaAcceso _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT RecepcionFichaAccesoDefaultTypeInternal _RecepcionFichaAcceso_default_instance_;
}  // namespace toDusPB
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_todus_2eproto[6];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_todus_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_todus_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_todus_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::toDusPB::SolicitudSMS, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::toDusPB::SolicitudSMS, telefono_),
  PROTOBUF_FIELD_OFFSET(::toDusPB::SolicitudSMS, id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::toDusPB::SolicitudFichaSolicitud, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::toDusPB::SolicitudFichaSolicitud, telefono_),
  PROTOBUF_FIELD_OFFSET(::toDusPB::SolicitudFichaSolicitud, id_),
  PROTOBUF_FIELD_OFFSET(::toDusPB::SolicitudFichaSolicitud, codigo_),
  PROTOBUF_FIELD_OFFSET(::toDusPB::RecepcionFichaSolicitud_DatosUsuario, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::toDusPB::RecepcionFichaSolicitud_DatosUsuario, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::toDusPB::RecepcionFichaSolicitud_DatosUsuario, telefono_),
  PROTOBUF_FIELD_OFFSET(::toDusPB::RecepcionFichaSolicitud_DatosUsuario, nombre_),
  PROTOBUF_FIELD_OFFSET(::toDusPB::RecepcionFichaSolicitud_DatosUsuario, enlacefoto_),
  PROTOBUF_FIELD_OFFSET(::toDusPB::RecepcionFichaSolicitud_DatosUsuario, reservado1_),
  PROTOBUF_FIELD_OFFSET(::toDusPB::RecepcionFichaSolicitud_DatosUsuario, reservado2_),
  ~0u,
  0,
  1,
  2,
  3,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::toDusPB::RecepcionFichaSolicitud, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::toDusPB::RecepcionFichaSolicitud, fichasolicitud_),
  PROTOBUF_FIELD_OFFSET(::toDusPB::RecepcionFichaSolicitud, usuario_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::toDusPB::SolicitudFichaAcceso, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::toDusPB::SolicitudFichaAcceso, telefono_),
  PROTOBUF_FIELD_OFFSET(::toDusPB::SolicitudFichaAcceso, fichasolicitud_),
  PROTOBUF_FIELD_OFFSET(::toDusPB::SolicitudFichaAcceso, numeroversion_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::toDusPB::RecepcionFichaAcceso, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::toDusPB::RecepcionFichaAcceso, reservado1_),
  PROTOBUF_FIELD_OFFSET(::toDusPB::RecepcionFichaAcceso, fichaacceso_),
  PROTOBUF_FIELD_OFFSET(::toDusPB::RecepcionFichaAcceso, tiempoexpiracion_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::toDusPB::SolicitudSMS)},
  { 7, -1, sizeof(::toDusPB::SolicitudFichaSolicitud)},
  { 15, 25, sizeof(::toDusPB::RecepcionFichaSolicitud_DatosUsuario)},
  { 30, -1, sizeof(::toDusPB::RecepcionFichaSolicitud)},
  { 37, -1, sizeof(::toDusPB::SolicitudFichaAcceso)},
  { 45, -1, sizeof(::toDusPB::RecepcionFichaAcceso)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::toDusPB::_SolicitudSMS_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::toDusPB::_SolicitudFichaSolicitud_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::toDusPB::_RecepcionFichaSolicitud_DatosUsuario_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::toDusPB::_RecepcionFichaSolicitud_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::toDusPB::_SolicitudFichaAcceso_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::toDusPB::_RecepcionFichaAcceso_default_instance_),
};

const char descriptor_table_protodef_todus_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\013todus.proto\022\007toDusPB\",\n\014SolicitudSMS\022\020"
  "\n\010telefono\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\"G\n\027Solicitu"
  "dFichaSolicitud\022\020\n\010telefono\030\001 \001(\t\022\n\n\002id\030"
  "\002 \001(\t\022\016\n\006codigo\030\003 \001(\t\"\254\002\n\027RecepcionFicha"
  "Solicitud\022\026\n\016fichaSolicitud\030\001 \001(\t\022>\n\007usu"
  "ario\030\002 \001(\0132-.toDusPB.RecepcionFichaSolic"
  "itud.DatosUsuario\032\270\001\n\014DatosUsuario\022\020\n\010te"
  "lefono\030\001 \001(\t\022\023\n\006nombre\030\002 \001(\tH\000\210\001\001\022\027\n\nenl"
  "aceFoto\030\003 \001(\tH\001\210\001\001\022\027\n\nreservado1\030\004 \001(\tH\002"
  "\210\001\001\022\027\n\nreservado2\030\005 \001(\tH\003\210\001\001B\t\n\007_nombreB"
  "\r\n\013_enlaceFotoB\r\n\013_reservado1B\r\n\013_reserv"
  "ado2\"W\n\024SolicitudFichaAcceso\022\020\n\010telefono"
  "\030\001 \001(\t\022\026\n\016fichaSolicitud\030\002 \001(\t\022\025\n\rnumero"
  "Version\030\003 \001(\t\"Y\n\024RecepcionFichaAcceso\022\022\n"
  "\nreservado1\030\001 \001(\005\022\023\n\013fichaAcceso\030\002 \001(\t\022\030"
  "\n\020tiempoExpiracion\030\003 \001(\005b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_todus_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_todus_2eproto = {
  false, false, 632, descriptor_table_protodef_todus_2eproto, "todus.proto", 
  &descriptor_table_todus_2eproto_once, nullptr, 0, 6,
  schemas, file_default_instances, TableStruct_todus_2eproto::offsets,
  file_level_metadata_todus_2eproto, file_level_enum_descriptors_todus_2eproto, file_level_service_descriptors_todus_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_todus_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_todus_2eproto);
  return descriptor_table_todus_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_todus_2eproto(&descriptor_table_todus_2eproto);
namespace toDusPB {

// ===================================================================

class SolicitudSMS::_Internal {
 public:
};

SolicitudSMS::SolicitudSMS(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:toDusPB.SolicitudSMS)
}
SolicitudSMS::SolicitudSMS(const SolicitudSMS& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  telefono_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_telefono().empty()) {
    telefono_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_telefono(), 
      GetArena());
  }
  id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_id().empty()) {
    id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_id(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:toDusPB.SolicitudSMS)
}

void SolicitudSMS::SharedCtor() {
telefono_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

SolicitudSMS::~SolicitudSMS() {
  // @@protoc_insertion_point(destructor:toDusPB.SolicitudSMS)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SolicitudSMS::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  telefono_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SolicitudSMS::ArenaDtor(void* object) {
  SolicitudSMS* _this = reinterpret_cast< SolicitudSMS* >(object);
  (void)_this;
}
void SolicitudSMS::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SolicitudSMS::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SolicitudSMS::Clear() {
// @@protoc_insertion_point(message_clear_start:toDusPB.SolicitudSMS)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  telefono_.ClearToEmpty();
  id_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SolicitudSMS::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string telefono = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_telefono();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "toDusPB.SolicitudSMS.telefono"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "toDusPB.SolicitudSMS.id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SolicitudSMS::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:toDusPB.SolicitudSMS)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string telefono = 1;
  if (this->telefono().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_telefono().data(), static_cast<int>(this->_internal_telefono().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "toDusPB.SolicitudSMS.telefono");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_telefono(), target);
  }

  // string id = 2;
  if (this->id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_id().data(), static_cast<int>(this->_internal_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "toDusPB.SolicitudSMS.id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:toDusPB.SolicitudSMS)
  return target;
}

size_t SolicitudSMS::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:toDusPB.SolicitudSMS)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string telefono = 1;
  if (this->telefono().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_telefono());
  }

  // string id = 2;
  if (this->id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SolicitudSMS::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:toDusPB.SolicitudSMS)
  GOOGLE_DCHECK_NE(&from, this);
  const SolicitudSMS* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SolicitudSMS>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:toDusPB.SolicitudSMS)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:toDusPB.SolicitudSMS)
    MergeFrom(*source);
  }
}

void SolicitudSMS::MergeFrom(const SolicitudSMS& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:toDusPB.SolicitudSMS)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.telefono().size() > 0) {
    _internal_set_telefono(from._internal_telefono());
  }
  if (from.id().size() > 0) {
    _internal_set_id(from._internal_id());
  }
}

void SolicitudSMS::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:toDusPB.SolicitudSMS)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SolicitudSMS::CopyFrom(const SolicitudSMS& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:toDusPB.SolicitudSMS)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SolicitudSMS::IsInitialized() const {
  return true;
}

void SolicitudSMS::InternalSwap(SolicitudSMS* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  telefono_.Swap(&other->telefono_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  id_.Swap(&other->id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata SolicitudSMS::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class SolicitudFichaSolicitud::_Internal {
 public:
};

SolicitudFichaSolicitud::SolicitudFichaSolicitud(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:toDusPB.SolicitudFichaSolicitud)
}
SolicitudFichaSolicitud::SolicitudFichaSolicitud(const SolicitudFichaSolicitud& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  telefono_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_telefono().empty()) {
    telefono_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_telefono(), 
      GetArena());
  }
  id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_id().empty()) {
    id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_id(), 
      GetArena());
  }
  codigo_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_codigo().empty()) {
    codigo_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_codigo(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:toDusPB.SolicitudFichaSolicitud)
}

void SolicitudFichaSolicitud::SharedCtor() {
telefono_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
codigo_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

SolicitudFichaSolicitud::~SolicitudFichaSolicitud() {
  // @@protoc_insertion_point(destructor:toDusPB.SolicitudFichaSolicitud)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SolicitudFichaSolicitud::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  telefono_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  codigo_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SolicitudFichaSolicitud::ArenaDtor(void* object) {
  SolicitudFichaSolicitud* _this = reinterpret_cast< SolicitudFichaSolicitud* >(object);
  (void)_this;
}
void SolicitudFichaSolicitud::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SolicitudFichaSolicitud::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SolicitudFichaSolicitud::Clear() {
// @@protoc_insertion_point(message_clear_start:toDusPB.SolicitudFichaSolicitud)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  telefono_.ClearToEmpty();
  id_.ClearToEmpty();
  codigo_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SolicitudFichaSolicitud::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string telefono = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_telefono();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "toDusPB.SolicitudFichaSolicitud.telefono"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "toDusPB.SolicitudFichaSolicitud.id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string codigo = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_codigo();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "toDusPB.SolicitudFichaSolicitud.codigo"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SolicitudFichaSolicitud::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:toDusPB.SolicitudFichaSolicitud)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string telefono = 1;
  if (this->telefono().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_telefono().data(), static_cast<int>(this->_internal_telefono().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "toDusPB.SolicitudFichaSolicitud.telefono");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_telefono(), target);
  }

  // string id = 2;
  if (this->id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_id().data(), static_cast<int>(this->_internal_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "toDusPB.SolicitudFichaSolicitud.id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_id(), target);
  }

  // string codigo = 3;
  if (this->codigo().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_codigo().data(), static_cast<int>(this->_internal_codigo().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "toDusPB.SolicitudFichaSolicitud.codigo");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_codigo(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:toDusPB.SolicitudFichaSolicitud)
  return target;
}

size_t SolicitudFichaSolicitud::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:toDusPB.SolicitudFichaSolicitud)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string telefono = 1;
  if (this->telefono().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_telefono());
  }

  // string id = 2;
  if (this->id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_id());
  }

  // string codigo = 3;
  if (this->codigo().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_codigo());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SolicitudFichaSolicitud::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:toDusPB.SolicitudFichaSolicitud)
  GOOGLE_DCHECK_NE(&from, this);
  const SolicitudFichaSolicitud* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SolicitudFichaSolicitud>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:toDusPB.SolicitudFichaSolicitud)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:toDusPB.SolicitudFichaSolicitud)
    MergeFrom(*source);
  }
}

void SolicitudFichaSolicitud::MergeFrom(const SolicitudFichaSolicitud& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:toDusPB.SolicitudFichaSolicitud)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.telefono().size() > 0) {
    _internal_set_telefono(from._internal_telefono());
  }
  if (from.id().size() > 0) {
    _internal_set_id(from._internal_id());
  }
  if (from.codigo().size() > 0) {
    _internal_set_codigo(from._internal_codigo());
  }
}

void SolicitudFichaSolicitud::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:toDusPB.SolicitudFichaSolicitud)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SolicitudFichaSolicitud::CopyFrom(const SolicitudFichaSolicitud& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:toDusPB.SolicitudFichaSolicitud)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SolicitudFichaSolicitud::IsInitialized() const {
  return true;
}

void SolicitudFichaSolicitud::InternalSwap(SolicitudFichaSolicitud* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  telefono_.Swap(&other->telefono_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  id_.Swap(&other->id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  codigo_.Swap(&other->codigo_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata SolicitudFichaSolicitud::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class RecepcionFichaSolicitud_DatosUsuario::_Internal {
 public:
  using HasBits = decltype(std::declval<RecepcionFichaSolicitud_DatosUsuario>()._has_bits_);
  static void set_has_nombre(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_enlacefoto(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_reservado1(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_reservado2(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

RecepcionFichaSolicitud_DatosUsuario::RecepcionFichaSolicitud_DatosUsuario(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:toDusPB.RecepcionFichaSolicitud.DatosUsuario)
}
RecepcionFichaSolicitud_DatosUsuario::RecepcionFichaSolicitud_DatosUsuario(const RecepcionFichaSolicitud_DatosUsuario& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  telefono_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_telefono().empty()) {
    telefono_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_telefono(), 
      GetArena());
  }
  nombre_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_nombre()) {
    nombre_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_nombre(), 
      GetArena());
  }
  enlacefoto_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_enlacefoto()) {
    enlacefoto_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_enlacefoto(), 
      GetArena());
  }
  reservado1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_reservado1()) {
    reservado1_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_reservado1(), 
      GetArena());
  }
  reservado2_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_reservado2()) {
    reservado2_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_reservado2(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:toDusPB.RecepcionFichaSolicitud.DatosUsuario)
}

void RecepcionFichaSolicitud_DatosUsuario::SharedCtor() {
telefono_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
nombre_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
enlacefoto_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
reservado1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
reservado2_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

RecepcionFichaSolicitud_DatosUsuario::~RecepcionFichaSolicitud_DatosUsuario() {
  // @@protoc_insertion_point(destructor:toDusPB.RecepcionFichaSolicitud.DatosUsuario)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RecepcionFichaSolicitud_DatosUsuario::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  telefono_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  nombre_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  enlacefoto_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  reservado1_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  reservado2_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void RecepcionFichaSolicitud_DatosUsuario::ArenaDtor(void* object) {
  RecepcionFichaSolicitud_DatosUsuario* _this = reinterpret_cast< RecepcionFichaSolicitud_DatosUsuario* >(object);
  (void)_this;
}
void RecepcionFichaSolicitud_DatosUsuario::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RecepcionFichaSolicitud_DatosUsuario::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void RecepcionFichaSolicitud_DatosUsuario::Clear() {
// @@protoc_insertion_point(message_clear_start:toDusPB.RecepcionFichaSolicitud.DatosUsuario)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  telefono_.ClearToEmpty();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      nombre_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      enlacefoto_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      reservado1_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      reservado2_.ClearNonDefaultToEmpty();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RecepcionFichaSolicitud_DatosUsuario::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string telefono = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_telefono();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "toDusPB.RecepcionFichaSolicitud.DatosUsuario.telefono"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string nombre = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_nombre();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "toDusPB.RecepcionFichaSolicitud.DatosUsuario.nombre"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string enlaceFoto = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_enlacefoto();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "toDusPB.RecepcionFichaSolicitud.DatosUsuario.enlaceFoto"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string reservado1 = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_reservado1();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "toDusPB.RecepcionFichaSolicitud.DatosUsuario.reservado1"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string reservado2 = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_reservado2();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "toDusPB.RecepcionFichaSolicitud.DatosUsuario.reservado2"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RecepcionFichaSolicitud_DatosUsuario::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:toDusPB.RecepcionFichaSolicitud.DatosUsuario)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string telefono = 1;
  if (this->telefono().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_telefono().data(), static_cast<int>(this->_internal_telefono().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "toDusPB.RecepcionFichaSolicitud.DatosUsuario.telefono");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_telefono(), target);
  }

  // string nombre = 2;
  if (_internal_has_nombre()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_nombre().data(), static_cast<int>(this->_internal_nombre().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "toDusPB.RecepcionFichaSolicitud.DatosUsuario.nombre");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_nombre(), target);
  }

  // string enlaceFoto = 3;
  if (_internal_has_enlacefoto()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_enlacefoto().data(), static_cast<int>(this->_internal_enlacefoto().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "toDusPB.RecepcionFichaSolicitud.DatosUsuario.enlaceFoto");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_enlacefoto(), target);
  }

  // string reservado1 = 4;
  if (_internal_has_reservado1()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_reservado1().data(), static_cast<int>(this->_internal_reservado1().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "toDusPB.RecepcionFichaSolicitud.DatosUsuario.reservado1");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_reservado1(), target);
  }

  // string reservado2 = 5;
  if (_internal_has_reservado2()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_reservado2().data(), static_cast<int>(this->_internal_reservado2().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "toDusPB.RecepcionFichaSolicitud.DatosUsuario.reservado2");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_reservado2(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:toDusPB.RecepcionFichaSolicitud.DatosUsuario)
  return target;
}

size_t RecepcionFichaSolicitud_DatosUsuario::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:toDusPB.RecepcionFichaSolicitud.DatosUsuario)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string telefono = 1;
  if (this->telefono().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_telefono());
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // string nombre = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_nombre());
    }

    // string enlaceFoto = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_enlacefoto());
    }

    // string reservado1 = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_reservado1());
    }

    // string reservado2 = 5;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_reservado2());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RecepcionFichaSolicitud_DatosUsuario::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:toDusPB.RecepcionFichaSolicitud.DatosUsuario)
  GOOGLE_DCHECK_NE(&from, this);
  const RecepcionFichaSolicitud_DatosUsuario* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RecepcionFichaSolicitud_DatosUsuario>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:toDusPB.RecepcionFichaSolicitud.DatosUsuario)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:toDusPB.RecepcionFichaSolicitud.DatosUsuario)
    MergeFrom(*source);
  }
}

void RecepcionFichaSolicitud_DatosUsuario::MergeFrom(const RecepcionFichaSolicitud_DatosUsuario& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:toDusPB.RecepcionFichaSolicitud.DatosUsuario)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.telefono().size() > 0) {
    _internal_set_telefono(from._internal_telefono());
  }
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_nombre(from._internal_nombre());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_enlacefoto(from._internal_enlacefoto());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_set_reservado1(from._internal_reservado1());
    }
    if (cached_has_bits & 0x00000008u) {
      _internal_set_reservado2(from._internal_reservado2());
    }
  }
}

void RecepcionFichaSolicitud_DatosUsuario::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:toDusPB.RecepcionFichaSolicitud.DatosUsuario)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RecepcionFichaSolicitud_DatosUsuario::CopyFrom(const RecepcionFichaSolicitud_DatosUsuario& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:toDusPB.RecepcionFichaSolicitud.DatosUsuario)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RecepcionFichaSolicitud_DatosUsuario::IsInitialized() const {
  return true;
}

void RecepcionFichaSolicitud_DatosUsuario::InternalSwap(RecepcionFichaSolicitud_DatosUsuario* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  telefono_.Swap(&other->telefono_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  nombre_.Swap(&other->nombre_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  enlacefoto_.Swap(&other->enlacefoto_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  reservado1_.Swap(&other->reservado1_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  reservado2_.Swap(&other->reservado2_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata RecepcionFichaSolicitud_DatosUsuario::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class RecepcionFichaSolicitud::_Internal {
 public:
  static const ::toDusPB::RecepcionFichaSolicitud_DatosUsuario& usuario(const RecepcionFichaSolicitud* msg);
};

const ::toDusPB::RecepcionFichaSolicitud_DatosUsuario&
RecepcionFichaSolicitud::_Internal::usuario(const RecepcionFichaSolicitud* msg) {
  return *msg->usuario_;
}
RecepcionFichaSolicitud::RecepcionFichaSolicitud(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:toDusPB.RecepcionFichaSolicitud)
}
RecepcionFichaSolicitud::RecepcionFichaSolicitud(const RecepcionFichaSolicitud& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  fichasolicitud_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_fichasolicitud().empty()) {
    fichasolicitud_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_fichasolicitud(), 
      GetArena());
  }
  if (from._internal_has_usuario()) {
    usuario_ = new ::toDusPB::RecepcionFichaSolicitud_DatosUsuario(*from.usuario_);
  } else {
    usuario_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:toDusPB.RecepcionFichaSolicitud)
}

void RecepcionFichaSolicitud::SharedCtor() {
fichasolicitud_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
usuario_ = nullptr;
}

RecepcionFichaSolicitud::~RecepcionFichaSolicitud() {
  // @@protoc_insertion_point(destructor:toDusPB.RecepcionFichaSolicitud)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RecepcionFichaSolicitud::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  fichasolicitud_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete usuario_;
}

void RecepcionFichaSolicitud::ArenaDtor(void* object) {
  RecepcionFichaSolicitud* _this = reinterpret_cast< RecepcionFichaSolicitud* >(object);
  (void)_this;
}
void RecepcionFichaSolicitud::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RecepcionFichaSolicitud::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void RecepcionFichaSolicitud::Clear() {
// @@protoc_insertion_point(message_clear_start:toDusPB.RecepcionFichaSolicitud)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  fichasolicitud_.ClearToEmpty();
  if (GetArena() == nullptr && usuario_ != nullptr) {
    delete usuario_;
  }
  usuario_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RecepcionFichaSolicitud::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string fichaSolicitud = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_fichasolicitud();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "toDusPB.RecepcionFichaSolicitud.fichaSolicitud"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .toDusPB.RecepcionFichaSolicitud.DatosUsuario usuario = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_usuario(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RecepcionFichaSolicitud::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:toDusPB.RecepcionFichaSolicitud)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string fichaSolicitud = 1;
  if (this->fichasolicitud().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_fichasolicitud().data(), static_cast<int>(this->_internal_fichasolicitud().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "toDusPB.RecepcionFichaSolicitud.fichaSolicitud");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_fichasolicitud(), target);
  }

  // .toDusPB.RecepcionFichaSolicitud.DatosUsuario usuario = 2;
  if (this->has_usuario()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::usuario(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:toDusPB.RecepcionFichaSolicitud)
  return target;
}

size_t RecepcionFichaSolicitud::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:toDusPB.RecepcionFichaSolicitud)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string fichaSolicitud = 1;
  if (this->fichasolicitud().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_fichasolicitud());
  }

  // .toDusPB.RecepcionFichaSolicitud.DatosUsuario usuario = 2;
  if (this->has_usuario()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *usuario_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RecepcionFichaSolicitud::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:toDusPB.RecepcionFichaSolicitud)
  GOOGLE_DCHECK_NE(&from, this);
  const RecepcionFichaSolicitud* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RecepcionFichaSolicitud>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:toDusPB.RecepcionFichaSolicitud)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:toDusPB.RecepcionFichaSolicitud)
    MergeFrom(*source);
  }
}

void RecepcionFichaSolicitud::MergeFrom(const RecepcionFichaSolicitud& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:toDusPB.RecepcionFichaSolicitud)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.fichasolicitud().size() > 0) {
    _internal_set_fichasolicitud(from._internal_fichasolicitud());
  }
  if (from.has_usuario()) {
    _internal_mutable_usuario()->::toDusPB::RecepcionFichaSolicitud_DatosUsuario::MergeFrom(from._internal_usuario());
  }
}

void RecepcionFichaSolicitud::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:toDusPB.RecepcionFichaSolicitud)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RecepcionFichaSolicitud::CopyFrom(const RecepcionFichaSolicitud& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:toDusPB.RecepcionFichaSolicitud)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RecepcionFichaSolicitud::IsInitialized() const {
  return true;
}

void RecepcionFichaSolicitud::InternalSwap(RecepcionFichaSolicitud* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  fichasolicitud_.Swap(&other->fichasolicitud_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(usuario_, other->usuario_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RecepcionFichaSolicitud::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class SolicitudFichaAcceso::_Internal {
 public:
};

SolicitudFichaAcceso::SolicitudFichaAcceso(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:toDusPB.SolicitudFichaAcceso)
}
SolicitudFichaAcceso::SolicitudFichaAcceso(const SolicitudFichaAcceso& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  telefono_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_telefono().empty()) {
    telefono_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_telefono(), 
      GetArena());
  }
  fichasolicitud_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_fichasolicitud().empty()) {
    fichasolicitud_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_fichasolicitud(), 
      GetArena());
  }
  numeroversion_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_numeroversion().empty()) {
    numeroversion_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_numeroversion(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:toDusPB.SolicitudFichaAcceso)
}

void SolicitudFichaAcceso::SharedCtor() {
telefono_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
fichasolicitud_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
numeroversion_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

SolicitudFichaAcceso::~SolicitudFichaAcceso() {
  // @@protoc_insertion_point(destructor:toDusPB.SolicitudFichaAcceso)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SolicitudFichaAcceso::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  telefono_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  fichasolicitud_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  numeroversion_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SolicitudFichaAcceso::ArenaDtor(void* object) {
  SolicitudFichaAcceso* _this = reinterpret_cast< SolicitudFichaAcceso* >(object);
  (void)_this;
}
void SolicitudFichaAcceso::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SolicitudFichaAcceso::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SolicitudFichaAcceso::Clear() {
// @@protoc_insertion_point(message_clear_start:toDusPB.SolicitudFichaAcceso)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  telefono_.ClearToEmpty();
  fichasolicitud_.ClearToEmpty();
  numeroversion_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SolicitudFichaAcceso::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string telefono = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_telefono();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "toDusPB.SolicitudFichaAcceso.telefono"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string fichaSolicitud = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_fichasolicitud();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "toDusPB.SolicitudFichaAcceso.fichaSolicitud"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string numeroVersion = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_numeroversion();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "toDusPB.SolicitudFichaAcceso.numeroVersion"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SolicitudFichaAcceso::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:toDusPB.SolicitudFichaAcceso)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string telefono = 1;
  if (this->telefono().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_telefono().data(), static_cast<int>(this->_internal_telefono().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "toDusPB.SolicitudFichaAcceso.telefono");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_telefono(), target);
  }

  // string fichaSolicitud = 2;
  if (this->fichasolicitud().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_fichasolicitud().data(), static_cast<int>(this->_internal_fichasolicitud().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "toDusPB.SolicitudFichaAcceso.fichaSolicitud");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_fichasolicitud(), target);
  }

  // string numeroVersion = 3;
  if (this->numeroversion().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_numeroversion().data(), static_cast<int>(this->_internal_numeroversion().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "toDusPB.SolicitudFichaAcceso.numeroVersion");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_numeroversion(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:toDusPB.SolicitudFichaAcceso)
  return target;
}

size_t SolicitudFichaAcceso::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:toDusPB.SolicitudFichaAcceso)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string telefono = 1;
  if (this->telefono().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_telefono());
  }

  // string fichaSolicitud = 2;
  if (this->fichasolicitud().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_fichasolicitud());
  }

  // string numeroVersion = 3;
  if (this->numeroversion().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_numeroversion());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SolicitudFichaAcceso::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:toDusPB.SolicitudFichaAcceso)
  GOOGLE_DCHECK_NE(&from, this);
  const SolicitudFichaAcceso* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SolicitudFichaAcceso>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:toDusPB.SolicitudFichaAcceso)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:toDusPB.SolicitudFichaAcceso)
    MergeFrom(*source);
  }
}

void SolicitudFichaAcceso::MergeFrom(const SolicitudFichaAcceso& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:toDusPB.SolicitudFichaAcceso)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.telefono().size() > 0) {
    _internal_set_telefono(from._internal_telefono());
  }
  if (from.fichasolicitud().size() > 0) {
    _internal_set_fichasolicitud(from._internal_fichasolicitud());
  }
  if (from.numeroversion().size() > 0) {
    _internal_set_numeroversion(from._internal_numeroversion());
  }
}

void SolicitudFichaAcceso::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:toDusPB.SolicitudFichaAcceso)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SolicitudFichaAcceso::CopyFrom(const SolicitudFichaAcceso& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:toDusPB.SolicitudFichaAcceso)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SolicitudFichaAcceso::IsInitialized() const {
  return true;
}

void SolicitudFichaAcceso::InternalSwap(SolicitudFichaAcceso* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  telefono_.Swap(&other->telefono_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  fichasolicitud_.Swap(&other->fichasolicitud_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  numeroversion_.Swap(&other->numeroversion_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata SolicitudFichaAcceso::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class RecepcionFichaAcceso::_Internal {
 public:
};

RecepcionFichaAcceso::RecepcionFichaAcceso(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:toDusPB.RecepcionFichaAcceso)
}
RecepcionFichaAcceso::RecepcionFichaAcceso(const RecepcionFichaAcceso& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  fichaacceso_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_fichaacceso().empty()) {
    fichaacceso_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_fichaacceso(), 
      GetArena());
  }
  ::memcpy(&reservado1_, &from.reservado1_,
    static_cast<size_t>(reinterpret_cast<char*>(&tiempoexpiracion_) -
    reinterpret_cast<char*>(&reservado1_)) + sizeof(tiempoexpiracion_));
  // @@protoc_insertion_point(copy_constructor:toDusPB.RecepcionFichaAcceso)
}

void RecepcionFichaAcceso::SharedCtor() {
fichaacceso_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&reservado1_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&tiempoexpiracion_) -
    reinterpret_cast<char*>(&reservado1_)) + sizeof(tiempoexpiracion_));
}

RecepcionFichaAcceso::~RecepcionFichaAcceso() {
  // @@protoc_insertion_point(destructor:toDusPB.RecepcionFichaAcceso)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RecepcionFichaAcceso::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  fichaacceso_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void RecepcionFichaAcceso::ArenaDtor(void* object) {
  RecepcionFichaAcceso* _this = reinterpret_cast< RecepcionFichaAcceso* >(object);
  (void)_this;
}
void RecepcionFichaAcceso::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RecepcionFichaAcceso::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void RecepcionFichaAcceso::Clear() {
// @@protoc_insertion_point(message_clear_start:toDusPB.RecepcionFichaAcceso)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  fichaacceso_.ClearToEmpty();
  ::memset(&reservado1_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&tiempoexpiracion_) -
      reinterpret_cast<char*>(&reservado1_)) + sizeof(tiempoexpiracion_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RecepcionFichaAcceso::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 reservado1 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          reservado1_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string fichaAcceso = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_fichaacceso();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "toDusPB.RecepcionFichaAcceso.fichaAcceso"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 tiempoExpiracion = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          tiempoexpiracion_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RecepcionFichaAcceso::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:toDusPB.RecepcionFichaAcceso)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 reservado1 = 1;
  if (this->reservado1() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_reservado1(), target);
  }

  // string fichaAcceso = 2;
  if (this->fichaacceso().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_fichaacceso().data(), static_cast<int>(this->_internal_fichaacceso().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "toDusPB.RecepcionFichaAcceso.fichaAcceso");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_fichaacceso(), target);
  }

  // int32 tiempoExpiracion = 3;
  if (this->tiempoexpiracion() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_tiempoexpiracion(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:toDusPB.RecepcionFichaAcceso)
  return target;
}

size_t RecepcionFichaAcceso::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:toDusPB.RecepcionFichaAcceso)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string fichaAcceso = 2;
  if (this->fichaacceso().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_fichaacceso());
  }

  // int32 reservado1 = 1;
  if (this->reservado1() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_reservado1());
  }

  // int32 tiempoExpiracion = 3;
  if (this->tiempoexpiracion() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_tiempoexpiracion());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RecepcionFichaAcceso::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:toDusPB.RecepcionFichaAcceso)
  GOOGLE_DCHECK_NE(&from, this);
  const RecepcionFichaAcceso* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RecepcionFichaAcceso>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:toDusPB.RecepcionFichaAcceso)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:toDusPB.RecepcionFichaAcceso)
    MergeFrom(*source);
  }
}

void RecepcionFichaAcceso::MergeFrom(const RecepcionFichaAcceso& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:toDusPB.RecepcionFichaAcceso)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.fichaacceso().size() > 0) {
    _internal_set_fichaacceso(from._internal_fichaacceso());
  }
  if (from.reservado1() != 0) {
    _internal_set_reservado1(from._internal_reservado1());
  }
  if (from.tiempoexpiracion() != 0) {
    _internal_set_tiempoexpiracion(from._internal_tiempoexpiracion());
  }
}

void RecepcionFichaAcceso::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:toDusPB.RecepcionFichaAcceso)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RecepcionFichaAcceso::CopyFrom(const RecepcionFichaAcceso& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:toDusPB.RecepcionFichaAcceso)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RecepcionFichaAcceso::IsInitialized() const {
  return true;
}

void RecepcionFichaAcceso::InternalSwap(RecepcionFichaAcceso* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  fichaacceso_.Swap(&other->fichaacceso_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RecepcionFichaAcceso, tiempoexpiracion_)
      + sizeof(RecepcionFichaAcceso::tiempoexpiracion_)
      - PROTOBUF_FIELD_OFFSET(RecepcionFichaAcceso, reservado1_)>(
          reinterpret_cast<char*>(&reservado1_),
          reinterpret_cast<char*>(&other->reservado1_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RecepcionFichaAcceso::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace toDusPB
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::toDusPB::SolicitudSMS* Arena::CreateMaybeMessage< ::toDusPB::SolicitudSMS >(Arena* arena) {
  return Arena::CreateMessageInternal< ::toDusPB::SolicitudSMS >(arena);
}
template<> PROTOBUF_NOINLINE ::toDusPB::SolicitudFichaSolicitud* Arena::CreateMaybeMessage< ::toDusPB::SolicitudFichaSolicitud >(Arena* arena) {
  return Arena::CreateMessageInternal< ::toDusPB::SolicitudFichaSolicitud >(arena);
}
template<> PROTOBUF_NOINLINE ::toDusPB::RecepcionFichaSolicitud_DatosUsuario* Arena::CreateMaybeMessage< ::toDusPB::RecepcionFichaSolicitud_DatosUsuario >(Arena* arena) {
  return Arena::CreateMessageInternal< ::toDusPB::RecepcionFichaSolicitud_DatosUsuario >(arena);
}
template<> PROTOBUF_NOINLINE ::toDusPB::RecepcionFichaSolicitud* Arena::CreateMaybeMessage< ::toDusPB::RecepcionFichaSolicitud >(Arena* arena) {
  return Arena::CreateMessageInternal< ::toDusPB::RecepcionFichaSolicitud >(arena);
}
template<> PROTOBUF_NOINLINE ::toDusPB::SolicitudFichaAcceso* Arena::CreateMaybeMessage< ::toDusPB::SolicitudFichaAcceso >(Arena* arena) {
  return Arena::CreateMessageInternal< ::toDusPB::SolicitudFichaAcceso >(arena);
}
template<> PROTOBUF_NOINLINE ::toDusPB::RecepcionFichaAcceso* Arena::CreateMaybeMessage< ::toDusPB::RecepcionFichaAcceso >(Arena* arena) {
  return Arena::CreateMessageInternal< ::toDusPB::RecepcionFichaAcceso >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
